[package]
author = "Alper Akça <alperakca79@outlook.com>"
name = "sum_all_numbers_in_range"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
