[package]
authors = ["Alper Akça <alperakca79@outlook.com>"]
name = "fizz_buzz"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
